# This is a basic workflow to help you get started with Actions

name: Docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dockerbuild:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Build and Push Action
      uses: docker/build-push-action@v1
      with:
        tags: latest
        repository: kikkirej/git-to-ssh-updater
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
